# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_status',
            field=models.CharField(choices=[('U', 'Unresponded'), ('A', 'Approved'), ('R', 'Rejected')], default='U', max_length=1),
        ),
    ]
