# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0002_auto_20170424_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverecorddetail',
            name='earned_leaves',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='leaverecorddetail',
            name='personal_leaves',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='leaverecorddetail',
            name='sick_leaves',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
