# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 11:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveManagement', '0003_auto_20170426_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverecorddetail',
            name='earned_leaves',
            field=models.PositiveIntegerField(default=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leaverecorddetail',
            name='personal_leaves',
            field=models.PositiveIntegerField(default=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leaverecorddetail',
            name='sick_leaves',
            field=models.PositiveIntegerField(default=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
